kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-data-local
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-sc
  capacity:
    storage: 10Gi
  local:
    path: /mnt/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-node-1
