apiVersion: apps/v1
kind: Deployment
metadata:
  labels:   # labels define key-value pairs. Each key must be unique
            # for a given object
    app: persistlogs
  name: persistlogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistlogs
  template:   # Template specifies the pod specification.
              # Each pod will be created using this template.
    metadata:
      labels:
        app: persistlogs     # Labels given to each podspec
    spec:
        # initContainers:         # Init containers finish before any other
                                # container can start.
                                # There can be many init containers.
                                # They run in the sequence given here.
                                # Each has to complete before the next is started.
                                # After the last completes, the containers are
                                # all started in parallel.
        #  - name: init-container
            # image: init-container:latest
      containers:             # Containers in this pod
        #        - name: sidecar       # Name of the container
        #          image: sidecar:latest
        #          imagePullPolicy: Never
        #          ports:
        #            - name: grpc-port
        #              containerPort: 5555 # Listens on this GRPC port.
        - name: persistlogs   # Name of the container
          image: persistlogs:latest
          imagePullPolicy: Never
          ports:
            - name: postgres-port
              containerPort: 5432 # Listens on this database port.
                # - name: grpc-port
                # containerPort: 5555 # Listens on this GRPC port.
          volumeMounts:
          - name: mnt-config
            mountPath: /mnt/config
            readOnly: true
          - name: mnt-secret
            mountPath: /mnt/secret
            readOnly: true
      volumes:
        - name: mnt-config
          configMap:  # This allows you to specify which items to include here.
            name: persistlogs-config
            items:
              - key: serviceName
                path: service-name.conf
        - name: mnt-secret
          secret:
            secretName: postgres-login
            items:
              - key: user
                path: user-value-path
              - key: pass
                path: pass-value-path
                mode: 0400
